---
version: "2.1"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /containers/sonarr/config:/config
      - nfsmediatv:/tv
      - /containers/transmission/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - USER=transmission #optional
      - PASS=password #optional
    volumes:
      - /containers/transmission/config:/config
      - /containers/transmission/downloads:/downloads
      - /containers/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
    volumes:
      - /containers/radarr/config:/config
      - nfsmediamovies:/movies
      - /containers/transmission/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - /containers/jackett/config:/config
      - /containers/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped 
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /containers/jellyfin/config:/config
      - /containers/jellyfin/cache:/cache
      - nfsmediatv:/media
      - nfsmediamovies:/media2:ro
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: "unless-stopped"
networks:
  default:
    external: 
      name: sonarr-net
volumes:
  nfsmediatv:
    external: true
    name: nfsmediatv
  nfsmediamovies:
    external: true
    name: nfsmediamovies
